spring:
  application:
    name: demo

  # JPA configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
    tomcat:
      test-on-borrow: true
      validation-query: SELECT 1

  jpa:
    hibernate:
      ddl-auto: create #validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    show-sql: ${SHOW_SQL:true}
    properties:
      hibernate:
        jdbc:
          batch_size: 10
        order_updates: true
        order_inserts: true
        format_sql: true
        generate_statistics: true
        default_schema: postgres

  # Flyway configuration
  flyway:
    baseline-on-migrate: true
    enabled: true
    validate-on-migrate: true
    baseline-version: 0
    schemas: postgres

bill:
  commission:
    type: PERCENT
    value: 10